### ISSUE TITLE
Message-via-Issue: Go devopenspace workshop follow up.

### ISSUE THREAD

**Issue by miku** [c3er/bin2img#1]
Hi, @miku here. This is not an issue, just a message-wrapped-in-an-issue.

Just wanted to let you know about [binpic](https://github.com/miku/binpic), a currently [125 lines of Go](https://github.com/miku/binpic/blob/e1241339364b9c3a4303cda172595d3724e89412/cmd/binpic/main.go) utility to create PNG images from files, including a [small gallery](https://github.com/miku/binpic#gallery). Cheers.

**Comment by c3er** [comment]
Hi, thanks for the information. Just forked the repository. I let this issue open until I have a closer look on this tool. I miss the colors. :)

**Comment by miku** [comment]
Yes, the colors. As a first iteration, I used grayscale to encode byte-by-byte. There is sure room for some nice color palettes.

**Comment by c3er** [comment]
[`bin2img.py`](https://github.com/c3er/bin2img/blob/master/bin2img/bin2img.py) uses a simple algorithm to generate a tuple of RGB from a byte value:

```python
def getcolor(byteval):
    return (
        ((byteval & 0o300) >> 6) * 64,
        ((byteval & 0o070) >> 3) * 32,
        (byteval & 0o007) * 32,
)
```

I'll make a pull request one time, if you're not faster. Though an option for grayscale or color or even for choosing a color palette would be nice, too.

Here is an example (putty.exe):

![putty.exe](https://user-images.githubusercontent.com/24460532/47620788-bcd5cd00-daee-11e8-97fa-b2877cd31d37.png)

**Comment by c3er** [comment]
I just extended my `bin2img.py` to generate Grey scale images optionally. Now it's just a question of months until I extend your `binpic` to generate color images optionally. :)

**Comment by c3er** [comment]
Closing this issue after I sent you a [PR](https://github.com/miku/binpic/pull/1). :)
